// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleList: typeof import('./components/ArticleList/ArticleList.vue')['default']
    Articles: typeof import('./components/Articles/Articles.vue')['default']
    Collects: typeof import('./components/Collects/Collects.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Lables: typeof import('./components/Lables/Lables.vue')['default']
    LogInRegister: typeof import('./components/logInRegister/logInRegister.vue')['default']
    MyHome: typeof import('./components/MyHome/MyHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryBg: typeof import('./components/SecondaryBg/SecondaryBg.vue')['default']
    SecondaryBgTwo: typeof import('./components/SecondaryBg/SecondaryBgTwo.vue')['default']
    SecondaryComments: typeof import('./components/SecondaryComments/SecondaryComments.vue')['default']
    'SecondaryComments副本': typeof import('./components/SecondaryComments/SecondaryComments副本.vue')['default']
    SecondaryCommentsMessage: typeof import('./components/SecondaryComments/SecondaryCommentsMessage.vue')['default']
    Waterfall: typeof import('./components/Waterfall/Waterfall.vue')['default']
    WriteAnEssay: typeof import('./components/WriteAnEssay/WriteAnEssay.vue')['default']
  }
}
