// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleList: typeof import('./components/ArticleList/ArticleList.vue')['default']
    Articles: typeof import('./components/Articles/Articles.vue')['default']
    Collects: typeof import('./components/Collects/Collects.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./components/Footer/Footer.vue')['default']
    Lables: typeof import('./components/Lables/Lables.vue')['default']
    LogInRegister: typeof import('./components/logInRegister/logInRegister.vue')['default']
    MyHome: typeof import('./components/MyHome/MyHome.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecondaryBg: typeof import('./components/SecondaryBg/SecondaryBg.vue')['default']
    SecondaryBgTwo: typeof import('./components/SecondaryBg/SecondaryBgTwo.vue')['default']
    SecondaryComments: typeof import('./components/SecondaryComments/SecondaryComments.vue')['default']
    'SecondaryComments副本': typeof import('./components/SecondaryComments/SecondaryComments副本.vue')['default']
    SecondaryCommentsMessage: typeof import('./components/SecondaryComments/SecondaryCommentsMessage.vue')['default']
    Waterfall: typeof import('./components/Waterfall/Waterfall.vue')['default']
    WriteAnEssay: typeof import('./components/WriteAnEssay/WriteAnEssay.vue')['default']
  }
}
